common: &COMMON_SETTINGS
  aws_s3_signer:
    access_key_id: 'DUMMY'
    secret_access_key: 'DUMMY'

development:
  << : *COMMON_SETTINGS

test:
  << : *COMMON_SETTINGS

profiler:
  << : *COMMON_SETTINGS

production:
  << : *COMMON_SETTINGS
